# Generated by Django 3.1.12 on 2025-09-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('ocrtime', models.CharField(max_length=10)),
                ('digitheight', models.CharField(max_length=10)),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('right', models.IntegerField()),
                ('bottom', models.IntegerField()),
                ('confidencecode', models.CharField(max_length=5)),
                ('controldigit', models.CharField(max_length=5)),
                ('numdigits', models.CharField(max_length=5)),
                ('ownercity', models.CharField(max_length=100)),
                ('ownercode', models.CharField(max_length=20)),
                ('ownercompany', models.CharField(max_length=100)),
                ('readconfidence', models.CharField(max_length=10)),
                ('serialcode', models.CharField(max_length=50)),
                ('sizetypecode', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
