# Generated by Django 3.1.12 on 2026-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tagreader'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradata',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
