# Generated by Django 3.1.12 on 2026-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cameradata_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagreader',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
